services:
  chromadb:
    image: ghcr.io/chroma-core/chroma:0.4.13
    environment:
      - IS_PERSISTENT=TRUE
    ports:
      - "8000:8000"
    volumes:
      - chroma-data:/chroma/chroma/
volumes:
  chroma-data:
    driver: local